version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8080"  # Cambié el puerto de la máquina local a 8081
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://anthonyjpg89:lw3U04PxNNOMBuZA@cluster0.botgqem.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
